### ISSUE TITLE
CTAP error: 0x27 - OPERATION_DENIED

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitro-python#1] opened 2019-09-13 14:52 UTC
Several commands yields to the same error. Example `make-credential` and `reset`.
```
$ solo key make-credential
Touch your authenticator to generate a credential...
Traceback (most recent call last):
  File "/home/jan/.local/lib/python3.6/site-packages/fido2/client.py", line 308, in make_credential
    pin, timeout, on_keepalive
  File "/home/jan/.local/lib/python3.6/site-packages/fido2/client.py", line 348, in _ctap2_make_credential
    pin_protocol, timeout, on_keepalive)
  File "/home/jan/.local/lib/python3.6/site-packages/fido2/ctap2.py", line 642, in make_credential
    ), timeout, AttestationObject, on_keepalive)
  File "/home/jan/.local/lib/python3.6/site-packages/fido2/ctap2.py", line 606, in send_cbor
    raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x27 - OPERATION_DENIED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jan/.local/bin/solo", line 11, in <module>
    sys.exit(solo_cli())
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jan/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jan/.local/lib/python3.6/site-packages/solo/cli/key.py", line 151, in make_credential
    host=host, user_id=user, serial=serial, output=True, prompt=prompt, udp=udp
  File "/home/jan/.local/lib/python3.6/site-packages/solo/hmac_secret.py", line 44, in make_credential
    rp, user, challenge, extensions=hmac_ext.create_dict(), pin=pin
  File "/home/jan/.local/lib/python3.6/site-packages/fido2/client.py", line 311, in make_credential
    raise _ctap2client_err(e)
fido2.client.ClientError: (<ERR.BAD_REQUEST: 2>, CtapError('CTAP error: 0x27 - OPERATION_DENIED',))
```

**Comment by szszszsz** [comment] 2019-12-20 13:00
These errors were caused by immediate deny of the FIDO2 request. Now the in-device polling for the UP check is activated, and issue should manifest anymore.
Closing as fixed.

**Closed by szszszsz** 2019-12-20 13:00 UTC
